### PR TITLE
[JENKINS-41805] Add deleteTmpDir option

### PR DESCRIPTION
**Pull request by m4x1202**
This would make it possible to also cleanup the ``@tmp`` directory of a workspace.
Default value is set to false to be backward compatible.

### CODE REVIEW

**Comment by pjanouse** [comment]
@jglick Although [JENKINS-41805](https://issues.jenkins-ci.org/browse/JENKINS-41805) looks a serious issue for me (unresolved yet), I don't think it is a fault of WS Cleanup plugin itself. It shouldn't remove an orphan besides `${env.WORKSPACE}` directory.

Do we want to introduce this feature in WS Cleanup plugin or we rather fix the issue elsewhere?

It isn't only about `${env.WORKSPACE}@tmp` location, but also `${env.WORKSPACE}@script` and who can know what brings the future...

**Comment by AnEmortalKid** [comment]
Would an option for additional patterns added to `${env.WORKSPACE}` be acceptable? Something like:
```
cleanWs(siblings: ["@tmp", "@script"]
```

**Comment by saraogivinay** [comment]
Anyone update on when this PR can be merged?

**Comment by olivergondza** [comment]
I am sorry but this functionality does not belong to ws-cleanup plugin. Putting aside it is not a workspace, it is a utility directory created by some other plugin that should be responsible for cleaning it. As I have stated in the JIRA, removing the pipeline work-directories by this plugin while the pipeline is still in progress is brittle as hell.

I do understand this is impactfull and it causes a lot of pain, but this is not a way to improve that.

**Comment by jglick** [comment]
> it is a utility directory created by some other plugin

`@tmp` is standard in Jenkins (see `WorkspaceList`).

**Comment by jakubgs** [comment]
Indeed, the `@tmp` folder is part of standard Jenkins functionality, just check `/env-vars.html`:

>`WORKSPACE_TMP`
>A temporary directory near the workspace that will not be browsable and will not interfere with SCM checkouts. May not initially exist, so be sure to create the directory as needed (e.g., mkdir -p on Linux). Not defined when the regular workspace is a drive root.

**Comment by jakubgs** [comment]
Nearly 3 years later and this is still a problem, and this issue was closed without a good reason.

The `@tmp` directories are part of normal Jenkins functionality as described above, and this plugin should remove them. Sad.

**Pull request closed without merging**
