### PR TITLE
Grab FilePath each time in case Channel is dead.

### PR DESCRIPTION
**Pull request by mmitche**
This bug shows up as a memory leak in systems that have a lot of node delete operations shortly after jobs are finished.  FIlePath contains a reference to the channel.  When the node is deleted (or the connection dies, etc.) the channel is no longer valid, causing exceptions (of various types).  These exceptions are then interpreted as a need to retry, and we will slowly build up operations in the async cleanup backlog until jenkins runs out of memory.

Instead, grab the computer (which would be null if we lost connection) and remote workspace each time we want to attempt cleanup.

### CODE REVIEW

**Comment by mmitche** [comment]
@olivergondza I can't repro these failures locally.  I would have expected the mocking failures to show up just the same, anyways, can you look?  Fixes https://issues.jenkins-ci.org/browse/JENKINS-43831

**Comment by olivergondza** [comment]
The change makes sense to me. Please drop a comment to the code noting why caching the `FilePath` is a bad idea - I have not though of this.

**Comment by mmitche** [comment]
@olivergondza Added, thanks!

**Comment by olivergondza** [comment]
Thanks!

**Pull request merged**
